### ISSUE TITLE
options.retain on subscribe()

### ISSUE THREAD

**Issue by forty2** [hobbyquaker/mqtt-scripts#2]
The API docs for subscribe() say that you can pass in a ```{ retain: true }``` option to get notified of retained messages in addition to "regular" changes, but it doesn't seem to be working.  I did a bit of digging through the code and it looks like it may either be on purpose, or possibly a feature that isn't finished yet -- there's a timeout that ensures there are no subscriptions before retained messages have been received, and in any case the ```'message'``` event handler never calls ```stateChange()``` for retained messages anyway.

So, what I'm wondering is, is it supposed to work?  Also, I notice that there haven't been any commits for quite some time; do you have any unpublished changes you might like to share?

Background context:
I've been putting together my own automation system based on mqtt-smarthome principles, and up till now I've been using my own cobbled-together script runner for logic.  However, you've done a much better job than I did at making a script-runner, and rather than trying to add some of the fancier features to mine (like cron and solar scheduling support) I'm trying to convert my scripts to run in this environment.

**Comment by hobbyquaker** [comment]
Oh yes - you're right. I already fixed that on my local version, will update the github repo this weekend :)

**Comment by hobbyquaker** [comment]
Published v0.11.0 - the issue you described "should" be fixed there. Have to clean this up now, bump many dependencies, this project was way to long unmaintained ;-)
