### ISSUE TITLE
No executable available after installation

### ISSUE THREAD

**Issue by nanosonde** [hobbyquaker/mqtt-scripts#4]
Hi!
If one is strictly following the installation procedure with the command 
```
sudo npm install -g mqtt-scripts
```
then afterwards there is no executable to call in the PATH.
However, it is working for other node scripts after installing them globally.

Any idea what's wrong?
```
pi@rpi3-knx:/home $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
pi@rpi3-knx:/home $ node -v
v8.11.3
pi@rpi3-knx:/home $ npm -v
6.3.0
```

**Comment by hobbyquaker** [comment]
Oh, oops ;-) I forgot to set the `bin` property in package.json. Will fix that asap. Meanwhile you could create the link manually: `ln -s /usr/local/lib/node_modules/mqtt-scripts/index.js /usr/local/bin/mqtt-scripts`
