### ISSUE TITLE
Process is undefined

### ISSUE THREAD

**Issue by jesseschutt** [hobbyquaker/mqtt-scripts#8]
Thanks for this package - it's been very helpful!

I'm attempting to add some env values to my scripts but I can't seem to get access to `process` when I run `mqtt-scripts`.  A console log of `process` indicates it is not defined.

Is there something I'm missing?

**Comment by dlashua** [comment]
Each script is run in a sandbox. If process isn't exposed in the sandbox, then it isn't available in the script. I'm pretty sure you'll need to modify index.js to expose "process" to the sandbox.
